#!/bin/bash

export PATH="${PATH}:${CRISIS_SCSS_DIR}"

STATIC_DIR="${CRISIS_ROOT}/static"
mkdir $STATIC_DIR
WEBCONTENT_DIR="${CRISIS_ROOT}/webcontent"

echo "-----> compiling scss"
sass "${WEBCONTENT_DIR}/css/main.scss" "${STATIC_DIR}/main.css"

echo "-----> compiling js"
pushd "${WEBCONTENT_DIR}/js" > /dev/null
{
    OUTPUT="${STATIC_DIR}/compiled.js" 
    INPUT="goog.js \
           main.js \
           prototypes.js \
           controls.js \
           event.js \
           coords.js \
           bounds.js \
           ajax.js \
           division.js \
           divisionMapMarker.js \
           divisiondetails.js \
           unittype.js \
           unittype-li.js \
           unit-type-chooser.js \
           faction.js \
           faction-li.js \
           faction-selector.js \
           faction-visibility-selector.js \
           unit.js \
           details-unit-li.js \
           map.js \
           routepoint.js"
    EXTERNS="jquiexterns.js \
             jsonexterns.js \
             jquery-1.9.js \
             underscore-1.5.1.js \
             bucketsexterns.js"
    java -jar "${CRISIS_CLOSURE_COMPILER_DIR}/compiler.jar" \
         --compilation_level SIMPLE_OPTIMIZATIONS \
         --js $INPUT --externs $EXTERNS --js_output_file $OUTPUT \
         --generate_exports --warning_level VERBOSE \
         --jscomp_warning=checkTypes --jscomp_warning=missingProperties
    cp -r "${WEBCONTENT_DIR}/js/thirdparty/." "${STATIC_DIR}/"
    mkdir "${STATIC_DIR}/bgs"
    cp -r "${CRISIS_IMAGE_PATH}/." "${STATIC_DIR}/bgs/"
} >> "${CRISIS_LOG_DIR}/go.log"
