runtime: go
env: flex

env_variables:
  DB_USERNAME: crisis
  DB_PASSWORD: <PASSWORD>
  DB_HOST:     /cloudsql/<SQL_INSTANCE>/.s.PGSQL.5432
  DB_PORT:     5432
  CLOUD_BUCKET_NAME: <BUCKET_NAME>

beta_settings:
  cloud_sql_instances: <SQL_INSTANCE>

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: _go_app
