runtime: go
env: flex

env_variables:
  DB_USERNAME: crisis
  DB_PASSWORD: <PASSWORD>
  DB_HOST:     /cloudsql/crisis-188722:us-east1:crisis-test
  DB_PORT:     5432

beta_settings:
  cloud_sql_instances: crisis-188722:us-east1:crisis-test

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: _go_app
